//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.12 at 02:04:11 PM MST 
//


package com.immco.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for endPoint.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="endPoint">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="/surveyComplete"/>
 *     &lt;enumeration value="/estimateComplete"/>
 *     &lt;enumeration value="/estimateSupApprove"/>
 *     &lt;enumeration value="/walkoutComplete"/>
 *     &lt;enumeration value="/designComplete"/>
 *     &lt;enumeration value="/permitComplete"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "endPoint")
@XmlEnum
public enum EndPoint {

    @XmlEnumValue("/surveyComplete")
    SURVEY_COMPLETE("/surveyComplete"),
    @XmlEnumValue("/estimateComplete")
    ESTIMATE_COMPLETE("/estimateComplete"),
    @XmlEnumValue("/estimateSupApprove")
    ESTIMATE_SUP_APPROVE("/estimateSupApprove"),
    @XmlEnumValue("/walkoutComplete")
    WALKOUT_COMPLETE("/walkoutComplete"),
    @XmlEnumValue("/designComplete")
    DESIGN_COMPLETE("/designComplete"),
    @XmlEnumValue("/permitComplete")
    PERMIT_COMPLETE("/permitComplete");
    private final String value;

    EndPoint(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EndPoint fromValue(String v) {
        for (EndPoint c: EndPoint.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
