//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.12 at 02:04:11 PM MST 
//


package com.immco.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for uiBean.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="uiBean">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="com.immco.survey.SurveyUI"/>
 *     &lt;enumeration value="com.immco.survey.EstimatePopup"/>
 *     &lt;enumeration value="com.immco.survey.WalkoutUI"/>
 *     &lt;enumeration value="com.immco.survey.RoiUI"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "uiBean")
@XmlEnum
public enum UiBean {

    @XmlEnumValue("com.immco.survey.SurveyUI")
    COM_IMMCO_SURVEY_SURVEY_UI("com.immco.survey.SurveyUI"),
    @XmlEnumValue("com.immco.survey.EstimatePopup")
    COM_IMMCO_SURVEY_ESTIMATE_POPUP("com.immco.survey.EstimatePopup"),
    @XmlEnumValue("com.immco.survey.WalkoutUI")
    COM_IMMCO_SURVEY_WALKOUT_UI("com.immco.survey.WalkoutUI"),
    @XmlEnumValue("com.immco.survey.RoiUI")
    COM_IMMCO_SURVEY_ROI_UI("com.immco.survey.RoiUI");
    private final String value;

    UiBean(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static UiBean fromValue(String v) {
        for (UiBean c: UiBean.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
